server:
  port: 8080
  servlet:
    context-path: /wechat-platform

spring:
  profiles:
    active: @spring.profiles.active@

wechat:
  mp:
    configs:
      - rawId:
        appId:
        appSecret:
        encodingAESKey:
        token:
  wecom:
    configs:
      - agentId:
        corpId:
        appSecret:
        encodingAESKey:
        token: