server:
  port: 8080
  servlet:
    context-path: /wechat-platform

wechat:
  mp:
    configs:
      - rawId:
        appId:
        appSecret:
        encodingAESKey:
        token:
  wecom:
    configs:
      - agentId:
        corpId:
        appSecret:
        encodingAESKey:
        token: